// Template-drift mode — `mode: template-drift`.
//
// For a repository generated by create-sato-agent: read sato.create.json and
// sato.lock.json from the repo root, ask Sato Hub's drift endpoint what has
// materially changed since the repo was generated (a newer green template, a
// custody reading that moved for a pinned package, an upstream release that
// broke the template), and make sure EXACTLY ONE issue exists per change, ever.
//
// "Ever" is literal. Each issue carries a hidden marker
// `<!-- sato-drift:<key> -->`. Before opening anything, every issue in the repo
// that could carry a marker is read — open AND closed. A closed issue is an
// answer ("seen it, not doing it") and is never reopened or duplicated. No pull
// requests are opened and no badge is written.
//
// Fails open: an unreachable API or a missing token is a warning, and the step
// exits non-zero only when the user set fail_on_error: true.
//
// Pure helpers are exported for tests; runDrift() does the I/O with injected
// clients (makeGitHub / makeDriftClient) so the tests run offline.

import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { UA, repoHeader } from "./custody.mjs";

export const DRIFT_TIMEOUT_MS = 30_000;
export const DRIFT_LABEL = "sato-drift";
export const MAX_PAGES = 50; // 100 per page; a repo with more issues than this falls back to the search API
export const CREATE_FILE = "sato.create.json";
export const LOCK_FILE = "sato.lock.json";

/** The hidden marker for one change key. `--` cannot appear inside an HTML comment. */
export function markerFor(key) {
  return `<!-- sato-drift:${String(key).replace(/--/g, "-‐").replace(/>/g, "›")} -->`;
}

const KIND_LABEL = {
  template_update: "Template update",
  custody_change: "Custody reading changed",
  upstream_break: "Upstream release broke the template",
};

/** Issue title + body for one change. The body is the API's own text plus the marker. */
export function issueFor(change) {
  const title = String(change.title || `${KIND_LABEL[change.kind] || "Template drift"}: ${change.key}`).slice(0, 240);
  const ev = Array.isArray(change.evidence_urls) ? change.evidence_urls.filter((u) => typeof u === "string") : [];
  const body = [
    markerFor(change.key),
    String(change.body_markdown || "").trim(),
    "",
    ev.length ? `**Evidence**\n\n${ev.map((u) => `- ${u}`).join("\n")}\n` : "",
    `_Opened once by \`satohubai/preflight-action\` in template-drift mode (change key \`${change.key}\`). Closing this issue is an answer: it will not be reopened or opened again._`,
  ].filter((s) => s !== "").join("\n");
  return { title, body, labels: [DRIFT_LABEL] };
}

/** Which changes still need an issue, given the set of issue bodies already in the repo. */
export function pendingChanges(changes, bodies) {
  const seen = new Set();
  const out = [];
  for (const c of changes || []) {
    if (!c || typeof c.key !== "string" || !c.key) continue;
    if (seen.has(c.key)) continue; // the API should not repeat a key; never open two for one
    seen.add(c.key);
    const m = markerFor(c.key);
    if (bodies.some((b) => typeof b === "string" && b.includes(m))) continue;
    out.push(c);
  }
  return out;
}

// ---------- clients ----------

export function makeDriftClient({ api, fetchFn = fetch }) {
  return {
    async drift(create, lock) {
      const res = await fetchFn(`${api.replace(/\/$/, "")}/api/create/drift`, {
        method: "POST",
        headers: { "content-type": "application/json", "user-agent": UA, accept: "application/json", ...repoHeader() },
        body: JSON.stringify({ create, lock }),
        signal: AbortSignal.timeout(DRIFT_TIMEOUT_MS),
      });
      const json = await res.json().catch(() => null);
      if (res.status !== 200 || !json) throw new Error(json?.error || `HTTP ${res.status}`);
      if (json.schema !== "sato.template-drift/v1" || !Array.isArray(json.changes)) throw new Error("unexpected response shape");
      return json;
    },
  };
}

export function makeGitHub({ repo, token, apiUrl = "https://api.github.com", fetchFn = fetch }) {
  const base = apiUrl.replace(/\/$/, "");
  const h = { authorization: `Bearer ${token}`, accept: "application/vnd.github+json", "user-agent": UA, "content-type": "application/json" };
  const get = async (path) => {
    const r = await fetchFn(`${base}${path}`, { headers: h, signal: AbortSignal.timeout(DRIFT_TIMEOUT_MS) });
    if (!r.ok) throw new Error(`GET ${path.split("?")[0]} answered HTTP ${r.status}`);
    return r.json();
  };
  const listAll = async (query) => {
    const bodies = [];
    for (let page = 1; page <= MAX_PAGES; page++) {
      const rows = await get(`/repos/${repo}/issues?state=all&per_page=100&page=${page}${query}`);
      if (!Array.isArray(rows)) break;
      for (const r of rows) bodies.push(r.body || "");
      if (rows.length < 100) return { bodies, complete: true };
    }
    return { bodies, complete: false };
  };
  return {
    /** Bodies of every labelled issue, open and closed. */
    labelled: () => listAll(`&labels=${encodeURIComponent(DRIFT_LABEL)}`),
    /** Bodies of every issue, open and closed — catches a marker whose label was removed. */
    all: () => listAll(""),
    /** Search API for one marker key, any state. Used when the full scan was capped. */
    async searchKey(key) {
      const q = encodeURIComponent(`repo:${repo} "sato-drift:${key}" in:body`);
      const j = await get(`/search/issues?q=${q}&per_page=100`);
      return (j.items || []).map((i) => i.body || "");
    },
    async create(issue) {
      const r = await fetchFn(`${base}/repos/${repo}/issues`, {
        method: "POST", headers: h, body: JSON.stringify(issue), signal: AbortSignal.timeout(DRIFT_TIMEOUT_MS),
      });
      if (!r.ok) throw new Error(`could not open an issue (HTTP ${r.status}) — the token needs issues: write`);
      const j = await r.json().catch(() => ({}));
      return { number: j.number, url: j.html_url };
    },
  };
}

// ---------- the run ----------

function readJson(path) {
  if (!existsSync(path)) return { missing: true };
  try { return { value: JSON.parse(readFileSync(path, "utf8")) }; } catch (e) { return { error: e?.message || String(e) }; }
}

function renderSummary({ drift, opened, existing, errors }) {
  const t = drift?.template || {};
  const lines = ["## Sato template drift", ""];
  if (t.id) {
    lines.push(`Template \`${t.id}/${t.framework}\` — pinned \`${t.pinned_version ?? "?"}\`, latest green \`${t.latest_version ?? "?"}\`${t.latest_last_green ? ` (${t.latest_last_green})` : ""}.`, "");
  }
  const changes = drift?.changes || [];
  if (!changes.length) {
    lines.push("No material change since this repository was generated.");
  } else {
    lines.push("| change | kind | issue |", "|---|---|---|");
    for (const c of changes) {
      const o = opened.find((x) => x.key === c.key);
      const where = o ? (o.url ? `[#${o.number}](${o.url}) opened` : "opened") : existing.has(c.key) ? "already filed (open or closed)" : "not opened";
      lines.push(`| ${String(c.title || c.key).replace(/\|/g, "\\|")} | \`${c.kind}\` | ${where} |`);
    }
  }
  if (errors.length) lines.push("", ...errors.map((e) => `> ${e}`));
  lines.push("", "_One issue per change, ever: a closed issue is never reopened or filed again. No pull requests are opened._");
  return lines.join("\n");
}

/**
 * Never throws. Returns { code, opened, existing, changes, skipped? }.
 * io: { cwd, env, log, summary, drift (client), github (client) }.
 */
export async function runDrift({ api, token = "", failOnError = false, io = {} } = {}) {
  const env = io.env || process.env;
  const log = io.log || console.log;
  const summary = io.summary || (() => {});
  const cwd = io.cwd || env.GITHUB_WORKSPACE || process.cwd();
  const soft = (msg) => { log(`::warning::${msg}`); return { code: failOnError ? 1 : 0, opened: [], existing: [], changes: [], error: msg }; };

  const create = readJson(join(cwd, CREATE_FILE));
  if (create.missing) {
    log(`::notice::Sato template drift: no ${CREATE_FILE} at the repository root, so this is not a create-sato-agent repository. Nothing to do.`);
    return { code: 0, opened: [], existing: [], changes: [], skipped: "no sato.create.json" };
  }
  if (create.error) return soft(`Sato template drift: ${CREATE_FILE} is not valid JSON (${create.error}).`);
  const lock = readJson(join(cwd, LOCK_FILE));
  if (lock.error) return soft(`Sato template drift: ${LOCK_FILE} is not valid JSON (${lock.error}).`);

  let drift;
  try {
    drift = await (io.drift || makeDriftClient({ api })).drift(create.value, lock.missing ? null : lock.value);
  } catch (e) {
    return soft(`Sato template drift: the drift endpoint was unreachable or refused (${e?.message || e}). No issues were opened.`);
  }
  const changes = drift.changes;
  if (!changes.length) {
    summary(renderSummary({ drift, opened: [], existing: new Set(), errors: [] }));
    log("Sato template drift: no material change.");
    return { code: 0, opened: [], existing: [], changes };
  }

  const repo = env.GITHUB_REPOSITORY;
  if (!token || !repo) {
    summary(renderSummary({ drift, opened: [], existing: new Set(), errors: ["No github-token or GITHUB_REPOSITORY; issues were not opened."] }));
    return soft("Sato template drift: no github-token, so issues were not opened. The job summary lists the changes.");
  }
  const gh = io.github || makeGitHub({ repo, token, apiUrl: env.GITHUB_API_URL || "https://api.github.com" });

  // Read every issue that could carry a marker BEFORE opening anything.
  let bodies;
  try {
    const labelled = await gh.labelled();
    bodies = [...labelled.bodies];
    let pending = pendingChanges(changes, bodies);
    if (pending.length) {
      // Fallback: a marker on an issue whose label was removed.
      const all = await gh.all();
      bodies.push(...all.bodies);
      pending = pendingChanges(changes, bodies);
      if (pending.length && (!all.complete || !labelled.complete)) {
        for (const c of pending) bodies.push(...(await gh.searchKey(c.key)));
      }
    }
  } catch (e) {
    // If we cannot prove an issue does not exist, we do not open one.
    summary(renderSummary({ drift, opened: [], existing: new Set(), errors: [`Could not read existing issues: ${e?.message || e}`] }));
    return soft(`Sato template drift: could not read existing issues (${e?.message || e}). No issues were opened, so none can be duplicated.`);
  }

  const toOpen = pendingChanges(changes, bodies);
  const existing = new Set(changes.map((c) => c.key).filter((k) => !toOpen.some((c) => c.key === k)));
  const opened = [];
  const errors = [];
  for (const c of toOpen) {
    try {
      const r = await gh.create(issueFor(c));
      opened.push({ key: c.key, ...r });
      log(`Sato template drift: opened #${r.number ?? "?"} for ${c.key}`);
    } catch (e) {
      errors.push(`${c.key}: ${e?.message || e}`);
    }
  }
  summary(renderSummary({ drift, opened, existing, errors }));
  if (errors.length) {
    log(`::warning::Sato template drift: ${errors.length} issue(s) could not be opened: ${errors.join("; ")}`);
    return { code: failOnError ? 1 : 0, opened, existing: [...existing], changes, error: errors.join("; ") };
  }
  return { code: 0, opened, existing: [...existing], changes };
}
